name: Monthly

on:
  schedule:
    - cron: '0,30 * * * *'  # once every 30 minutes

jobs:
  save-data:
    runs-on: macOS-latest
    env:
      ELEPHANT_SQL_DBNAME: ${{ secrets.ELEPHANT_SQL_DBNAME }}
      ELEPHANT_SQL_HOST: ${{ secrets.ELEPHANT_SQL_HOST }}
      ELEPHANT_SQL_USER: ${{ secrets.ELEPHANT_SQL_USER }}
      ELEPHANT_SQL_PASSWORD: ${{ secrets.ELEPHANT_SQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install package
        run: Rscript -e 'install.packages(c("dplyr", "rtweet", "rvest", "mongolite", "xml", "xml2"))'
      - name: Create and post tweet
        run: Rscript Monthly.R 
